import type { Project } from "@/types/project";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "1",
    title: "Neon Nights",
    modifiedDate: "Modified Sep 14, 2023",
    status: "In Post",
    timecode: "01:24:32:00",
    thumbnail: "https://picsum.photos/seed/neon-nights/800/450",
    thumbnailAlt: "Neon Nights Production",
    teamMembers: [
      { src: "https://i.pravatar.cc/100?u=member1", alt: "Team member" },
      { src: "https://i.pravatar.cc/100?u=member2", alt: "Team member" },
    ],
    extraMemberCount: 3,
    isOwner: true,
    currentUserRole: "Owner",
    generalAccess: "Just Crew",
  },
  {
    id: "2",
    title: "Dust & Glory",
    modifiedDate: "Modified Oct 02, 2023",
    status: "Shooting",
    timecode: "00:15:08:12",
    thumbnail: "https://picsum.photos/seed/dust-glory/800/450",
    thumbnailAlt: "Dust & Glory Production",
    teamMembers: [{ src: "https://i.pravatar.cc/100?u=member3", alt: "Team member" }],
    extraMemberCount: 8,
    isOwner: true,
    currentUserRole: "Owner",
    generalAccess: "Anyone with the link",
  },
  {
    id: "3",
    title: "Shadow Protocol",
    modifiedDate: "Modified Nov 18, 2023",
    status: "Ready",
    timecode: "02:44:11:00",
    thumbnail: "https://picsum.photos/seed/shadow-protocol/800/450",
    thumbnailAlt: "Shadow Protocol Production",
    teamMembers: [
      { src: "https://i.pravatar.cc/100?u=member4", alt: "Team member" },
      { src: "https://i.pravatar.cc/100?u=member5", alt: "Team member" },
    ],
    isOwner: false,
    currentUserRole: "Manager",
    generalAccess: "Just Crew",
  },
  {
    id: "4",
    title: "The Archive",
    modifiedDate: "Modified Dec 01, 2023",
    status: "Pre-Prod",
    timecode: "00:45:00:00",
    thumbnail: "https://picsum.photos/seed/the-archive/800/450",
    thumbnailAlt: "The Archive Production",
    teamMembers: [{ initials: "JD" }],
    isOwner: true,
    currentUserRole: "Owner",
    generalAccess: "Just Crew",
  },
  {
    id: "5",
    title: "Urban Pulse",
    modifiedDate: "Modified Dec 05, 2023",
    status: "In Post",
    timecode: "00:12:15:05",
    thumbnail: "https://picsum.photos/seed/urban-pulse/800/450",
    thumbnailAlt: "Urban Pulse Production",
    teamMembers: [{ src: "https://i.pravatar.cc/100?u=member6", alt: "Team member" }],
    isOwner: false,
    currentUserRole: "User",
    generalAccess: "Anyone with the link",
  },
];
